name: Check Software

on: workflow_dispatch

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Update APT
              run: sudo apt-get update
            - name: Install fortune and cowsay
              run: sudo apt-get install fortune cowsay
            - name: Test fortune
              run: /usr/games/fortune | /usr/games/cowsay

